name: CI

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

concurrency:
  group: cmake-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: cmake configure
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/dist -DBUILD_TESTING=OFF -DTOYWASM_BUILD_CLI=OFF -DTOYWASM_BUILD_UNITTEST=OFF -DTOYWASM_ENABLE_WASI=OFF

    - name: cmake -L
      run: |
        cmake -B build -L

    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --build build --target install

    - name: Test examples/run
      run: |
        cmake -B build -DCMAKE_PREFIX_PATH=${{github.workspace}}/dist
        cmake --build build
        .\build\Debug\run.exe ${{github.workspace}}/wat/fib.wasm test-all
      working-directory: ${{github.workspace}}/examples/run
