name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      CC: ${{matrix.compiler}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [clang, gcc]
        BUILD_TYPE: [Release, Debug]
        TOYWASM_USE_SEPARATE_EXECUTE: [ON, OFF]
        TOYWASM_USE_TAILCALL: [ON, OFF]
        TOYWASM_ENABLE_TRACING: [ON, OFF]
        TOYWASM_USE_SMALL_CELLS: [ON, OFF]
        TOYWASM_USE_SEPARATE_LOCALS: [ON, OFF]
        TOYWASM_ENABLE_WASM_THREADS: [ON, OFF]
        TOYWASM_ENABLE_WASI_THREADS: [ON, OFF]
        exclude:
          - TOYWASM_USE_SEPARATE_EXECUTE: OFF
            TOYWASM_USE_TAILCALL: ON
          - os: macos-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - TOYWASM_USE_SEPARATE_EXECUTE: ON
            TOYWASM_USE_TAILCALL: OFF
          - TOYWASM_USE_SMALL_CELLS: ON
            TOYWASM_USE_SEPARATE_LOCALS: ON
          - TOYWASM_ENABLE_WASM_THREADS: OFF
            TOYWASM_ENABLE_WASI_THREADS: ON
          - os: ubuntu-latest
            BUILD_TYPE: Release

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{matrix.os}}

    steps:
    - name: Install dependencies (ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      run: sudo apt-get update && sudo apt-get install -y wabt libcmocka-dev clang lld llvm-dev pax virtualenv

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install wabt
        brew install cmocka
        brew install virtualenv

    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
          -DTOYWASM_USE_SEPARATE_EXECUTE=${{matrix.TOYWASM_USE_SEPARATE_EXECUTE}} \
          -DTOYWASM_USE_TAILCALL=${{matrix.TOYWASM_USE_TAILCALL}} \
          -DTOYWASM_ENABLE_TRACING=${{matrix.TOYWASM_ENABLE_TRACING}} \
          -DTOYWASM_ENABLE_TRACING_INSN=${{matrix.TOYWASM_ENABLE_TRACING}} \
          -DTOYWASM_USE_SMALL_CELLS=${{matrix.TOYWASM_USE_SMALL_CELLS}} \
          -DTOYWASM_USE_SEPARATE_LOCALS=${{matrix.TOYWASM_USE_SEPARATE_LOCALS}} \
          -DTOYWASM_ENABLE_WASM_THREADS=${{matrix.TOYWASM_ENABLE_WASM_THREADS}} \
          -DTOYWASM_ENABLE_WASI_THREADS=${{matrix.TOYWASM_ENABLE_WASI_THREADS}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ./toywasm --version
        ctest -C ${{matrix.BUILD_TYPE}} -V -LE slow

    - name: Test (slow)
      if: matrix.BUILD_TYPE == 'Release'
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ./toywasm --version
        ctest -C ${{matrix.BUILD_TYPE}} -V -L slow

  wasm-on-wasm:
    env:
      CC: ${{matrix.compiler}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12]
        compiler: [clang]

    runs-on: ${{matrix.os}}

    steps:
    - name: Install dependencies (ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      run: sudo apt-get update && sudo apt-get install -y pax

    - uses: actions/checkout@v3

    - name: Build and test
      run: ./wasm-on-wasm.sh

  cross:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler: [clang]
        arch: [arm64, s390x, armhf]

    runs-on: ${{matrix.os}}

    steps:
    - name: Install dependencies (ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      run: sudo apt-get update && sudo apt-get install -y pax virtualenv

    - uses: actions/checkout@v3

    - name: Fix sources.list
      run: |
        curl -L -O https://raw.githubusercontent.com/yamt/garbage/master/myubuntu/apt/sources.list
        sudo cp sources.list /etc/apt/

    - name: Cross build
      env:
        ARCH: ${{matrix.arch}}
      run: |
        sudo -E ./cross/cross-setup.sh
        ./cross/cross-build.sh

    - name: Install QEMU
      run: |
        sudo apt-get update && sudo apt-get install -y qemu-user-static

    - name: Run
      env:
        ARCH: ${{matrix.arch}}
      run: |
        cd build.cross.${ARCH}
        ./toywasm --version
        ctest -V -LE slow

    - name: Run (slow)
      # skip for s390x as it's slow
      if: matrix.arch != 's390x'
      env:
        ARCH: ${{matrix.arch}}
      run: |
        cd build.cross.${ARCH}
        ./toywasm --version
        ctest -V -L slow
